# manifesto que gerencia os containers

version: '3'

services:
  nginx:
    image: nginx
    volumes: 
      - ./nginx:/usr/share/nginx/html/
    ports:
      - 8080:80
  redis: 
    image: redis
    expose:
      - 6379